In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../dataset/이자보상배율최종.csv", encoding='cp949')
backtest_2011=pd.read_csv("../년도별 주식데이터/2011년 주식데이터.csv", encoding='cp949',index_col=0)
backtest_2012=pd.read_csv("../년도별 주식데이터/2012년 주식데이터.csv", encoding='cp949',index_col=0)
backtest_2013=pd.read_csv("../년도별 주식데이터/2013년 주식데이터.csv", encoding='cp949',index_col=0)
backtest_2014=pd.read_csv("../년도별 주식데이터/2014년 주식데이터.csv", encoding='cp949',index_col=0)
backtest_2015=pd.read_csv("../년도별 주식데이터/2015년 주식데이터.csv", encoding='cp949',index_col=0)
backtest_2016=pd.read_csv("../년도별 주식데이터/2016년 주식데이터.csv", encoding='cp949',index_col=0)
backtest_2017=pd.read_csv("../년도별 주식데이터/2017년 주식데이터.csv", encoding='cp949',index_col=0)
backtest_2018=pd.read_csv("../년도별 주식데이터/2018년 주식데이터.csv", encoding='cp949',index_col=0)
backtest_2019=pd.read_csv("../년도별 주식데이터/2019년 주식데이터.csv", encoding='cp949',index_col=0)
backtest_2020=pd.read_csv("../년도별 주식데이터/2020년 주식데이터.csv", encoding='cp949',index_col=0)
backtest_kosdak=pd.read_csv("../년도별 주식데이터/코스닥주가.csv", encoding='cp949')

In [3]:
for i in data.index:
    data.loc[i,"회계년도"]=data.loc[i,"회계년도"].replace('-12-', '-04-')
    data.loc[i,"상장일"]=data.loc[i,"상장일"].replace('-',"")
 
data.rename(columns={'회계년도':'투자일자'},inplace=True)
data

,회사명,거래소코드,투자일자,상장일,상장폐지일,산업명,소속코드,[제조]매출액증가율,[제조]유형자산증가율,[제조]비유동자산증가율,...,[제조]기계투자효율,[제조]부가가치율,[제조]노동소득분배율,[제조]자본분배율,[제조]이윤분배율,[제조]유형자산회전율,[제조]이자보상배율(이자비용),year,month,label
0,(주)CMG제약,58820,2011-04-01,20010831,NaN,의료용 물질 및 의약품 제조업,5,56.40,-5.90,-12.89,...,128.51,19.56,89.82,10.18,-43.44,1.77,3.530000,2011,12,0
1,(주)CMG제약,58820,2012-04-01,20010831,NaN,의료용 물질 및 의약품 제조업,5,-8.43,-4.12,-16.43,...,10.67,1.66,1749.87,-1649.87,-2473.07,1.71,-7.750000,2012,12,0
2,(주)CMG제약,58820,2013-04-01,20010831,NaN,의료용 물질 및 의약품 제조업,5,25.51,16.09,77.05,...,289.40,34.29,71.28,28.72,4.23,2.03,0.700000,2013,12,0
3,(주)CMG제약,58820,2014-04-01,20010831,NaN,의료용 물질 및 의약품 제조업,5,11.52,74.30,68.15,...,132.06,31.04,79.30,20.70,2.24,1.54,3.600000,2014,12,0
4,(주)CMG제약,58820,2015-04-01,20010831,NaN,의료용 물질 및 의약품 제조업,5,18.85,-5.37,1.66,...,90.92,15.96,144.10,-44.10,-84.58,1.48,-32.220000,2015,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10647,흥구석유(주),24060,2016-04-01,19941207,NaN,도매 및 상품 중개업,5,-7.26,-5.61,0.11,...,3684.02,4.86,48.08,51.92,31.14,3.67,7.660000,2016,12,0
10648,흥구석유(주),24060,2017-04-01,19941207,NaN,도매 및 상품 중개업,5,8.12,-0.56,-0.48,...,4786.26,4.39,47.63,52.37,30.24,4.10,5.910000,2017,12,0
10649,흥구석유(주),24060,2018-04-01,19941207,NaN,도매 및 상품 중개업,5,6.87,-0.36,-2.09,...,3064.10,4.44,47.47,52.53,32.14,4.40,12.660000,2018,12,0
10650,흥구석유(주),24060,2019-04-01,19941207,NaN,도매 및 상품 중개업,5,-9.35,-7.00,-2.63,...,3489.21,10.00,22.19,77.81,55.02,4.14,252.020000,2019,12,0
10651,흥구석유(주),24060,2020-04-01,19941207,NaN,도매 및 상품 중개업,5,-23.78,-13.92,-8.21,...,3280.80,8.94,30.41,69.59,46.65,3.52,40.446667,2020,12,0

In [4]:
#logit 피처선정별 종류의 피처
data_mda = data[['회사명', '거래소코드', '투자일자', '상장일', '상장폐지일', '산업명', '소속코드','[제조]1주당순이익', '[제조]총자본투자효율','[제조]부가가치', '[제조]매출액순이익률', 
                 '[제조]자기자본배율', '[제조]총자본증가율','[제조]유형자산증가율',"[제조]유동비율",'[제조]비유동자산회전률','[제조]매입채무회전률' ]]
data_logit=data[['회사명', '거래소코드', '투자일자', '상장일', '상장폐지일', '산업명', '소속코드','[제조]총자본증가율', '[제조]총자본사업이익률', '[제조]1주당매출액', 
                '[제조]비유동자산회전률', '[제조]매출채권회전률', '[제조]순운전자본회전률', '[제조]현금비율', '[제조]자기자본배율', '[제조]노동소득분배율','[제조]이자보상배율(이자비용)']]
data_lasso = data[['회사명', '거래소코드', '투자일자', '상장일', '상장폐지일', '산업명', '소속코드','[제조]비유동자산증가율','[제조]자기자본증가율','[제조]재고자산증가율','[제조]매출액순이익률',
                '[제조]매입채무회전기간','[제조]재고자산회전기간','[제조]당좌자산회전률','[제조]현금비율','[제조]순운전자본비율','[제조]자기자본배율']]
data_elastic = data[['회사명', '거래소코드', '투자일자', '상장일', '상장폐지일', '산업명', '소속코드','[제조]비유동자산증가율','[제조]자기자본증가율','[제조]재고자산증가율',
                     '[제조]매출액순이익률','[제조]매입채무회전기간','[제조]재고자산회전기간','[제조]당좌자산회전률','[제조]현금비율','[제조]순운전자본비율','[제조]자기자본배율']]
data_same = data[['회사명', '거래소코드', '투자일자', '상장일', '상장폐지일', '산업명', '소속코드','[제조]노동소득분배율','[제조]자기자본배율','[제조]현금비율','[제조]자기자본증가율',
                  '[제조]총자본증가율','[제조]재고자산증가율','[제조]매출액순이익률','[제조]매입채무회전기간','[제조]재고자산회전기간','[제조]순운전자본회전률']]

In [5]:
# 수익성 범주인 총자본사업이익률과 [제조]1주당매출액의 4분위수에 공통적으로 있는 기업들 추출
data_logit=data_logit[(data_logit["[제조]비유동자산회전률"]>=data_logit["[제조]비유동자산회전률"].quantile(.75)) & (data_logit["[제조]1주당매출액"]>=data_logit["[제조]1주당매출액"].quantile(.75))
                                                                                            & (data_logit["[제조]현금비율"]>=data_logit["[제조]현금비율"].quantile(.75))]
# 상관계수가 높았던 총자본사업이익률 기준으로 추출

data_logit = data_logit.sort_values("[제조]1주당매출액",ascending=False)

data_logit

,회사명,거래소코드,투자일자,상장일,상장폐지일,산업명,소속코드,[제조]총자본증가율,[제조]총자본사업이익률,[제조]1주당매출액,[제조]비유동자산회전률,[제조]매출채권회전률,[제조]순운전자본회전률,[제조]현금비율,[제조]자기자본배율,[제조]노동소득분배율,[제조]이자보상배율(이자비용)
936,(주)디앤씨미디어,263720,2017-04-01,20170801,NaN,출판업,5,271.11,15.69,2586442.92,9.77,9.77,0.73,164.91,531.09,30.78,2234.663333
2041,(주)서산,79650,2015-04-01,20050121,NaN,비금속 광물제품 제조업,5,24.75,22.25,282490.34,2.94,6.04,1.54,254.02,3082.57,43.45,1929.460000
2038,(주)서산,79650,2012-04-01,20050121,NaN,비금속 광물제품 제조업,5,26.08,24.95,209868.36,3.23,6.59,2.06,104.35,2037.02,46.49,863.322500
9733,인탑스(주),49070,2013-04-01,20020221,NaN,"전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",5,-4.53,9.14,122409.88,3.90,17.57,2.58,93.05,8352.02,48.79,24.800000
3611,(주)에이치엘사이언스,239610,2016-04-01,20161028,NaN,식료품 제조업,5,214.03,19.52,117607.74,3.01,20.51,1.23,180.67,1952.07,26.34,621284.640000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1720,(주)블루콤,33560,2015-04-01,20110126,NaN,"전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",5,14.86,19.04,11305.22,3.32,13.45,1.62,222.06,1667.03,40.36,1003.770000
5393,(주)제이티,89790,2012-04-01,20061027,NaN,기타 기계 및 장비 제조업,5,-31.24,10.81,11298.28,4.16,8.50,2.09,128.64,643.80,55.78,22.820000
777,(주)동아엘텍,88130,2013-04-01,20070103,NaN,기타 기계 및 장비 제조업,5,39.89,12.11,11287.50,3.04,4.57,0.86,113.04,1599.68,50.34,11.130000
4271,(주)와이지엔터테인먼트,122870,2013-04-01,20111123,NaN,영상ㆍ오디오 기록물 제작 및 배급업,5,12.39,19.00,11260.19,3.70,8.34,1.03,114.84,2059.54,35.10,21.051429
2764,(주)씨티케이,260930,2017-04-01,20171207,NaN,화학물질 및 화학제품 제조업; 의약품 제외,5,148.71,13.71,11162.70,5.21,5.89,0.64,340.90,3390.76,22.14,3085.870000

In [6]:
# 년도별로 분류
data_logit_2011 = data_logit[data_logit["투자일자"]=='2011-04-01']
data_logit_2012 = data_logit[data_logit["투자일자"]=='2012-04-01']
data_logit_2012["투자일자"] = "2012-04-02"
data_logit_2013 = data_logit[data_logit["투자일자"]=='2013-04-01']
data_logit_2014 = data_logit[data_logit["투자일자"]=='2014-04-01']
data_logit_2015 = data_logit[data_logit["투자일자"]=='2015-04-01']
data_logit_2016 = data_logit[data_logit["투자일자"]=='2016-04-01']
data_logit_2017 = data_logit[data_logit["투자일자"]=='2017-04-01']
data_logit_2017["투자일자"] = "2017-04-03"
data_logit_2018 = data_logit[data_logit["투자일자"]=='2018-04-01']
data_logit_2018["투자일자"] = "2018-04-02"
data_logit_2019 = data_logit[data_logit["투자일자"]=='2019-04-01']
data_logit_2020 = data_logit[data_logit["투자일자"]=='2020-04-01']

<ipython-input-6-3ce73cae502e>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_logit_2012["투자일자"] = "2012-04-02"
<ipython-input-6-3ce73cae502e>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_logit_2017["투자일자"] = "2017-04-03"
<ipython-input-6-3ce73cae502e>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_logit_2018["투자일자"] = "2018-04-02"

In [7]:
data_logit_2011_buy=data_logit_2011[data_logit_2011["상장일"]<='20110401']
data_logit_2012_buy=data_logit_2012[data_logit_2012["상장일"]<='20120401']
data_logit_2013_buy=data_logit_2013[data_logit_2013["상장일"]<='20130401']
data_logit_2014_buy=data_logit_2014[data_logit_2014["상장일"]<='20140401']
data_logit_2015_buy=data_logit_2015[data_logit_2015["상장일"]<='20150401']
data_logit_2016_buy=data_logit_2016[data_logit_2016["상장일"]<='20160401']
data_logit_2017_buy=data_logit_2017[data_logit_2017["상장일"]<='20170401']
data_logit_2018_buy=data_logit_2018[data_logit_2018["상장일"]<='20180401']
data_logit_2019_buy=data_logit_2019[data_logit_2019["상장일"]<='20190401']
data_logit_2020_buy=data_logit_2020[data_logit_2020["상장일"]<='20200401']

In [8]:
# 해당기업 순위 20위 추출
data_logit_2011_buy=data_logit_2011_buy[:20]
data_logit_2012_buy=data_logit_2012_buy[:20]
data_logit_2013_buy=data_logit_2013_buy[:20]
data_logit_2014_buy=data_logit_2014_buy[:20]
data_logit_2015_buy=data_logit_2015_buy[:20]
data_logit_2016_buy=data_logit_2016_buy[:20]
data_logit_2017_buy=data_logit_2017_buy[:20]
data_logit_2018_buy=data_logit_2018_buy[:20]
data_logit_2019_buy=data_logit_2019_buy[:20]
data_logit_2020_buy=data_logit_2020_buy[:20]

In [9]:
#트레이드 조건 주기
data_logit_2011_buy["trade"]="buy"
data_logit_2012_buy["trade"]="buy"
data_logit_2013_buy["trade"]="buy"
data_logit_2014_buy["trade"]="buy"
data_logit_2015_buy["trade"]="buy"
data_logit_2016_buy["trade"]="buy"
data_logit_2017_buy["trade"]="buy"
data_logit_2018_buy["trade"]="buy"
data_logit_2019_buy["trade"]="buy"
data_logit_2020_buy["trade"]="buy"

In [10]:
data_logit_2011

,회사명,거래소코드,투자일자,상장일,상장폐지일,산업명,소속코드,[제조]총자본증가율,[제조]총자본사업이익률,[제조]1주당매출액,[제조]비유동자산회전률,[제조]매출채권회전률,[제조]순운전자본회전률,[제조]현금비율,[제조]자기자본배율,[제조]노동소득분배율,[제조]이자보상배율(이자비용)
3914,(주)엘엑스세미콘,108320,2011-04-01,20100608,NaN,"전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",5,10.91,12.26,18536.73,13.53,10.36,1.10,256.61,2715.77,32.21,44555.210000
83,(주)골프존뉴딘홀딩스,121440,2011-04-01,20110520,NaN,출판업,5,100.90,21.67,17568.46,2.90,29.65,0.93,197.26,5680.88,32.02,1101.460000
4269,(주)와이지엔터테인먼트,122870,2011-04-01,20111123,NaN,영상ㆍ오디오 기록물 제작 및 배급업,5,142.32,27.63,15667.49,5.71,12.19,1.20,266.69,2879.00,24.65,21.051429
9853,제이앤유글로벌,86200,2011-04-01,20060607,2016-05-09,"전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",4,11.40,12.38,11774.82,4.58,9.63,1.52,101.34,1397.53,43.63,28.270000

In [11]:
stock_2011 = pd.merge(backtest_2011,data_logit_2011_buy, how='left',on=['회사명','투자일자','거래소코드'])
stock_2012 = pd.merge(backtest_2012,data_logit_2012_buy, how='left',on=['회사명','투자일자','거래소코드'])
stock_2013 = pd.merge(backtest_2013,data_logit_2013_buy, how='left',on=['회사명','투자일자','거래소코드'])
stock_2014 = pd.merge(backtest_2014,data_logit_2014_buy, how='left',on=['회사명','투자일자','거래소코드'])
stock_2015 = pd.merge(backtest_2015,data_logit_2015_buy, how='left',on=['회사명','투자일자','거래소코드'])
stock_2016 = pd.merge(backtest_2016,data_logit_2016_buy, how='left',on=['회사명','투자일자','거래소코드'])
stock_2017 = pd.merge(backtest_2017,data_logit_2017_buy, how='left',on=['회사명','투자일자','거래소코드'])
stock_2018 = pd.merge(backtest_2018,data_logit_2018_buy, how='left',on=['회사명','투자일자','거래소코드'])
stock_2019 = pd.merge(backtest_2019,data_logit_2019_buy, how='left',on=['회사명','투자일자','거래소코드'])
stock_2020 = pd.merge(backtest_2020,data_logit_2020_buy, how='left',on=['회사명','투자일자','거래소코드'])

In [12]:
stock_2011

,index,회사명,거래소코드,투자일자,종가,일일수익률,상장일,상장폐지일,산업명,소속코드,...,[제조]총자본사업이익률,[제조]1주당매출액,[제조]비유동자산회전률,[제조]매출채권회전률,[제조]순운전자본회전률,[제조]현금비율,[제조]자기자본배율,[제조]노동소득분배율,[제조]이자보상배율(이자비용),trade
0,53134,(주)CMG제약,58820,2011-04-01,1710,-0.001168,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,54907,(주)CMG제약,58820,2011-04-04,1708,-0.001170,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,55794,(주)CMG제약,58820,2011-04-05,1732,0.014052,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,56489,(주)CMG제약,58820,2011-04-06,1732,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,57415,(주)CMG제약,58820,2011-04-07,1735,0.001732,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232119,280536,흥구석유(주),24060,2012-03-26,1745,0.002874,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232120,281614,흥구석유(주),24060,2012-03-27,1720,-0.014327,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232121,282512,흥구석유(주),24060,2012-03-28,1720,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232122,284240,흥구석유(주),24060,2012-03-29,1735,0.008721,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232123,284276,흥구석유(주),24060,2012-03-30,1795,0.034582,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
list =[stock_2011,stock_2012,stock_2013,stock_2014,stock_2015,stock_2016,stock_2017,stock_2018,stock_2019,stock_2020]
list_grn =[stock_2011,stock_2012,stock_2013,stock_2014,stock_2015,stock_2016,stock_2017,stock_2018,stock_2019,stock_2020]

In [14]:
for i in range(len(list)):
    for j in list[i].index:
        if j>0:
            if list[i].loc[j-1,"trade"] == "buy":
                list[i].loc[j,"trade"] = "hold"
            elif  list[i].loc[j-1,"trade"] == "hold":
                if list[i].iloc[:,1][j] == list[i].iloc[:,1][j-1]:
                    list[i].loc[j,"trade"] = "hold"
                elif list[i].iloc[:,1][j] != list[i].iloc[:,1][j-1]:
                    list[i].loc[j-1,"trade"] = "sell"
                if j== list[i].tail(n=1).index:
                    list[i].loc[j,"trade"] = "sell"
                        
for i in range(len(list)):
    list[i] = list[i][["회사명","거래소코드","투자일자","종가","일일수익률","trade"]]
    list[i] = list[i].dropna()
    list[i] = list[i].sort_values('투자일자', ascending=True)
    list[i] = list[i].reset_index(drop='index')
    list[i] = list[i].groupby("투자일자")["일일수익률"].sum()/20

In [15]:
# acc_rtn2= 1
# for i in range(len(list)):
#     list[i]=list[i].reset_index()
#     for j in list[i].index:
        
#         list[i].loc[j,"연누적수익률"] = acc_rtn2*list[i].loc[j,"일일수익률"]
#         acc_rtn2 = list[i].loc[j,"연누적수익률"]

In [16]:
stock_2011[stock_2011["trade"]=="sell"]

,index,회사명,거래소코드,투자일자,종가,일일수익률,상장일,상장폐지일,산업명,소속코드,...,[제조]총자본사업이익률,[제조]1주당매출액,[제조]비유동자산회전률,[제조]매출채권회전률,[제조]순운전자본회전률,[제조]현금비율,[제조]자기자본배율,[제조]노동소득분배율,[제조]이자보상배율(이자비용),trade
83374,284993,(주)엘엑스세미콘,108320,2012-03-30,33950,0.013433,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sell
216292,284419,제이앤유글로벌,86200,2012-03-30,10500,-0.018692,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sell

In [17]:
#각 년도별 수익률 합치기
rtn =pd.concat(list)
rtn = pd.DataFrame(rtn)

In [18]:
#리밸런싱 날짜는 수익률 반영을 못하므로 제거
rtn["일일수익률"] =rtn["일일수익률"]*100
rtn =rtn.drop(index=["2011-04-01","2012-04-02","2013-04-01","2014-04-01","2015-04-01","2016-04-01","2017-04-03","2018-04-02","2019-04-01","2020-04-01"])
stock_rtn=rtn.reset_index()

In [19]:
stock_rtn=rtn.reset_index()
stock_rtn.columns=["투자일자","일일수익률(%)"]
stock_rtn["일일수익률"] =(stock_rtn["일일수익률(%)"]/100) +1
stock_rtn

            투자일자  일일수익률(%)     일일수익률
0     2011-04-04 -0.355076  0.996449
1     2011-04-05  0.089691  1.000897
2     2011-04-06 -0.095384  0.999046
3     2011-04-07  0.104232  1.001042
4     2011-04-08 -0.355504  0.996445
...          ...       ...       ...
2448  2021-03-25 -0.054217  0.999458
2449  2021-03-26 -0.000226  0.999998
2450  2021-03-29 -0.076579  0.999234
2451  2021-03-30 -0.046577  0.999534
2452  2021-03-31  0.480351  1.004804

[2453 rows x 3 columns]

In [20]:
# stock_rtn[stock_rtn["투자일자"]=='2012-03-30']248
# stock_rtn[stock_rtn["투자일자"]=='2013-03-29'] 494
# stock_rtn[stock_rtn["투자일자"]=='2014-03-31'] 740
# stock_rtn[stock_rtn["투자일자"]=='2015-03-31'] 983
# stock_rtn[stock_rtn["투자일자"]=='2016-03-31'] 1230
# stock_rtn[stock_rtn["투자일자"]=='2017-03-31'] 1477
# stock_rtn[stock_rtn["투자일자"]=='2018-03-30'] 1718
# stock_rtn[stock_rtn["투자일자"]=='2019-03-29'] 1959
# stock_rtn[stock_rtn["투자일자"]=='2020-03-31'] 2207
# stock_rtn[stock_rtn["투자일자"]=='2021-03-31'] 2452

In [21]:
acc_rtn=1
for i in stock_rtn.index:
    
    stock_rtn.loc[i,"누적수익률"] = acc_rtn*stock_rtn.loc[i,"일일수익률"]
    acc_rtn = stock_rtn.loc[i,"누적수익률"]
        

acc_rtn_1 = 1
for i in stock_rtn.index:
    if i <= 248:
        
        stock_rtn.loc[i,"연누적수익률"] = acc_rtn_1*stock_rtn.loc[i,"일일수익률"]
        acc_rtn_1 = stock_rtn.loc[i,"연누적수익률"]
        stock_rtn.loc[i,"투자연차"] = 1
        
acc_rtn_2 = 1
for i in stock_rtn.index:
    if 248 < i <= 494:
        stock_rtn.loc[i,"연누적수익률"] = acc_rtn_2*stock_rtn.loc[i,"일일수익률"]
        acc_rtn_2 = stock_rtn.loc[i,"연누적수익률"]
        stock_rtn.loc[i,"투자연차"] = 2
        
acc_rtn_3 = 1        
for i in stock_rtn.index:
    if  494< i <=740:
        stock_rtn.loc[i,"연누적수익률"] = acc_rtn_3*stock_rtn.loc[i,"일일수익률"]
        acc_rtn_3 = stock_rtn.loc[i,"연누적수익률"]
        stock_rtn.loc[i,"투자연차"] = 3
        
acc_rtn_4 = 1       
for i in stock_rtn.index:
    if 740 < i <= 983:
        stock_rtn.loc[i,"연누적수익률"] = acc_rtn_4*stock_rtn.loc[i,"일일수익률"]
        acc_rtn_4 = stock_rtn.loc[i,"연누적수익률"]
        stock_rtn.loc[i,"투자연차"] = 4
        
acc_rtn_5 = 1       
for i in stock_rtn.index:
    if  983< i <= 1230:
        stock_rtn.loc[i,"연누적수익률"] = acc_rtn_5*stock_rtn.loc[i,"일일수익률"]
        acc_rtn_5 = stock_rtn.loc[i,"연누적수익률"]
        stock_rtn.loc[i,"투자연차"] = 5

acc_rtn_6 = 1
for i in stock_rtn.index:
    if 1230 < i <= 1477:
        stock_rtn.loc[i,"연누적수익률"] = acc_rtn_6*stock_rtn.loc[i,"일일수익률"]
        acc_rtn_6 = stock_rtn.loc[i,"연누적수익률"]
        stock_rtn.loc[i,"투자연차"] = 6
        
acc_rtn_7 = 1
for i in stock_rtn.index:
    if 1477 < i <= 1718:
        stock_rtn.loc[i,"연누적수익률"] = acc_rtn_7*stock_rtn.loc[i,"일일수익률"]
        acc_rtn_7 = stock_rtn.loc[i,"연누적수익률"]
        stock_rtn.loc[i,"투자연차"] = 7

acc_rtn_8 = 1
for i in stock_rtn.index:
    if 1718 < i <= 1959:
        stock_rtn.loc[i,"연누적수익률"] = acc_rtn_8*stock_rtn.loc[i,"일일수익률"]
        acc_rtn_8 = stock_rtn.loc[i,"연누적수익률"]
        stock_rtn.loc[i,"투자연차"] = 8   
             
acc_rtn_9 = 1      
for i in stock_rtn.index:
    if 1959 < i <= 2207:
        stock_rtn.loc[i,"연누적수익률"] = acc_rtn_9*stock_rtn.loc[i,"일일수익률"]
        acc_rtn_9 = stock_rtn.loc[i,"연누적수익률"]
        stock_rtn.loc[i,"투자연차"] = 9
        
acc_rtn_10 = 1       
for i in stock_rtn.index:
    if 2207 < i <= 2452:
        stock_rtn.loc[i,"연누적수익률"] = acc_rtn_10*stock_rtn.loc[i,"일일수익률"]
        acc_rtn_10 = stock_rtn.loc[i,"연누적수익률"]
        stock_rtn.loc[i,"투자연차"] = 10

In [22]:
#코스닥 시작 데이터 61
# backtest_kosdak[backtest_kosdak["날짜"]=="2011-04-04"]
#코스닥 마지막 데이터 2522
#backtest_kosdak[backtest_kosdak["날짜"]=="2021-03-31"]

In [23]:
#코스닥 데이터 끌고오기
backtest_kosdak_buy= backtest_kosdak[61:2523]
backtest_kosdak_rtn = backtest_kosdak_buy.set_index("날짜")

In [24]:
backtest_kosdak_rtn =backtest_kosdak_rtn.drop(index=["2012-04-02","2013-04-01","2014-04-01","2015-04-01","2016-04-01","2017-04-03","2018-04-02","2019-04-01","2020-04-01"])
backtest_kosdak_rtn=backtest_kosdak_rtn.reset_index()

In [25]:
backtest_kosdak_rtn.columns = ["투자일자","코스닥종가","시가총액","코스닥수익률","코스닥시총수익률"]

In [26]:
#주식수익률과 코스닥 merge
stock_rtn_all = pd.merge(stock_rtn,backtest_kosdak_rtn,how="left",on="투자일자")

In [27]:
stock_rtn_all["코스닥수익률"]=stock_rtn_all["코스닥수익률"]*100

In [28]:
stock_rtn_all

,투자일자,일일수익률(%),일일수익률,누적수익률,연누적수익률,투자연차,코스닥종가,시가총액,코스닥수익률,코스닥시총수익률
0,2011-04-04,-0.355076,0.996449,0.996449,0.996449,1.0,534.90,105835314871792,0.533774,0.005763
1,2011-04-05,0.089691,1.000897,0.997343,0.997343,1.0,537.66,106138352312272,0.515984,0.002863
2,2011-04-06,-0.095384,0.999046,0.996392,0.996392,1.0,533.98,105387016008919,-0.684447,-0.007079
3,2011-04-07,0.104232,1.001042,0.997430,0.997430,1.0,534.97,105571037939827,0.185400,0.001746
4,2011-04-08,-0.355504,0.996445,0.993884,0.993884,1.0,534.20,105439281631189,-0.143933,-0.001248
...,...,...,...,...,...,...,...,...,...,...
2448,2021-03-25,-0.054217,0.999458,2.843945,1.964711,10.0,954.99,387311921085308,0.122665,0.001147
2449,2021-03-26,-0.000226,0.999998,2.843938,1.964706,10.0,956.70,388051677647507,0.179059,0.001910
2450,2021-03-29,-0.076579,0.999234,2.841760,1.963202,10.0,954.10,386977420485060,-0.271768,-0.002768
2451,2021-03-30,-0.046577,0.999534,2.840437,1.962287,10.0,958.06,388660278311558,0.415051,0.004349
2452,2021-03-31,0.480351,1.004804,2.854081,1.971713,10.0,956.17,388147690314283,-0.197274,-0.001319

In [29]:

stock_rtn_all["코스닥수익률(%)"]= stock_rtn_all["코스닥수익률"]
stock_rtn_all["코스닥일일수익률"] =(stock_rtn_all["코스닥수익률(%)"]/100) +1
stock_rtn_all

,투자일자,일일수익률(%),일일수익률,누적수익률,연누적수익률,투자연차,코스닥종가,시가총액,코스닥수익률,코스닥시총수익률,코스닥수익률(%),코스닥일일수익률
0,2011-04-04,-0.355076,0.996449,0.996449,0.996449,1.0,534.90,105835314871792,0.533774,0.005763,0.533774,1.005338
1,2011-04-05,0.089691,1.000897,0.997343,0.997343,1.0,537.66,106138352312272,0.515984,0.002863,0.515984,1.005160
2,2011-04-06,-0.095384,0.999046,0.996392,0.996392,1.0,533.98,105387016008919,-0.684447,-0.007079,-0.684447,0.993156
3,2011-04-07,0.104232,1.001042,0.997430,0.997430,1.0,534.97,105571037939827,0.185400,0.001746,0.185400,1.001854
4,2011-04-08,-0.355504,0.996445,0.993884,0.993884,1.0,534.20,105439281631189,-0.143933,-0.001248,-0.143933,0.998561
...,...,...,...,...,...,...,...,...,...,...,...,...
2448,2021-03-25,-0.054217,0.999458,2.843945,1.964711,10.0,954.99,387311921085308,0.122665,0.001147,0.122665,1.001227
2449,2021-03-26,-0.000226,0.999998,2.843938,1.964706,10.0,956.70,388051677647507,0.179059,0.001910,0.179059,1.001791
2450,2021-03-29,-0.076579,0.999234,2.841760,1.963202,10.0,954.10,386977420485060,-0.271768,-0.002768,-0.271768,0.997282
2451,2021-03-30,-0.046577,0.999534,2.840437,1.962287,10.0,958.06,388660278311558,0.415051,0.004349,0.415051,1.004151
2452,2021-03-31,0.480351,1.004804,2.854081,1.971713,10.0,956.17,388147690314283,-0.197274,-0.001319,-0.197274,0.998027

In [30]:
acc_rtn=1
for i in stock_rtn_all.index:
    
    stock_rtn_all.loc[i,'코스닥누적수익률'] = acc_rtn*stock_rtn_all.loc[i,"코스닥일일수익률"]
    acc_rtn = stock_rtn_all.loc[i,"코스닥누적수익률"]
    
    
stock_rtn_all

,투자일자,일일수익률(%),일일수익률,누적수익률,연누적수익률,투자연차,코스닥종가,시가총액,코스닥수익률,코스닥시총수익률,코스닥수익률(%),코스닥일일수익률,코스닥누적수익률
0,2011-04-04,-0.355076,0.996449,0.996449,0.996449,1.0,534.90,105835314871792,0.533774,0.005763,0.533774,1.005338,1.005338
1,2011-04-05,0.089691,1.000897,0.997343,0.997343,1.0,537.66,106138352312272,0.515984,0.002863,0.515984,1.005160,1.010525
2,2011-04-06,-0.095384,0.999046,0.996392,0.996392,1.0,533.98,105387016008919,-0.684447,-0.007079,-0.684447,0.993156,1.003609
3,2011-04-07,0.104232,1.001042,0.997430,0.997430,1.0,534.97,105571037939827,0.185400,0.001746,0.185400,1.001854,1.005469
4,2011-04-08,-0.355504,0.996445,0.993884,0.993884,1.0,534.20,105439281631189,-0.143933,-0.001248,-0.143933,0.998561,1.004022
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2448,2021-03-25,-0.054217,0.999458,2.843945,1.964711,10.0,954.99,387311921085308,0.122665,0.001147,0.122665,1.001227,1.777700
2449,2021-03-26,-0.000226,0.999998,2.843938,1.964706,10.0,956.70,388051677647507,0.179059,0.001910,0.179059,1.001791,1.780883
2450,2021-03-29,-0.076579,0.999234,2.841760,1.963202,10.0,954.10,386977420485060,-0.271768,-0.002768,-0.271768,0.997282,1.776043
2451,2021-03-30,-0.046577,0.999534,2.840437,1.962287,10.0,958.06,388660278311558,0.415051,0.004349,0.415051,1.004151,1.783415
2452,2021-03-31,0.480351,1.004804,2.854081,1.971713,10.0,956.17,388147690314283,-0.197274,-0.001319,-0.197274,0.998027,1.779896

In [31]:

for i in stock_rtn_all.index:
    if stock_rtn_all.iloc[:,5][i] == 1:
        stock_rtn_all.loc[i,"코스닥연누적수익률"] = stock_rtn_all.loc[i,"코스닥누적수익률"]
        
    elif stock_rtn_all.iloc[:,5][i] != 1:
        if stock_rtn_all.iloc[:,5][i] == stock_rtn_all.iloc[:,5][i-1]:
            stock_rtn_all.loc[i,"코스닥연누적수익률"] = stock_rtn_all.loc[i-1,"코스닥연누적수익률"]*stock_rtn_all.loc[i,"코스닥일일수익률"]
            
        elif stock_rtn_all.iloc[:,5][i] != stock_rtn_all.iloc[:,5][i-1]:
            stock_rtn_all.loc[i,"코스닥연누적수익률"] = stock_rtn_all.loc[i,"코스닥일일수익률"]

In [32]:
stock_rtn_all.iloc[:,5]

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ...
2448    10.0
2449    10.0
2450    10.0
2451    10.0
2452    10.0
Name: 투자연차, Length: 2453, dtype: float64

In [33]:
stock_rtn_all

,투자일자,일일수익률(%),일일수익률,누적수익률,연누적수익률,투자연차,코스닥종가,시가총액,코스닥수익률,코스닥시총수익률,코스닥수익률(%),코스닥일일수익률,코스닥누적수익률,코스닥연누적수익률
0,2011-04-04,-0.355076,0.996449,0.996449,0.996449,1.0,534.90,105835314871792,0.533774,0.005763,0.533774,1.005338,1.005338,1.005338
1,2011-04-05,0.089691,1.000897,0.997343,0.997343,1.0,537.66,106138352312272,0.515984,0.002863,0.515984,1.005160,1.010525,1.010525
2,2011-04-06,-0.095384,0.999046,0.996392,0.996392,1.0,533.98,105387016008919,-0.684447,-0.007079,-0.684447,0.993156,1.003609,1.003609
3,2011-04-07,0.104232,1.001042,0.997430,0.997430,1.0,534.97,105571037939827,0.185400,0.001746,0.185400,1.001854,1.005469,1.005469
4,2011-04-08,-0.355504,0.996445,0.993884,0.993884,1.0,534.20,105439281631189,-0.143933,-0.001248,-0.143933,0.998561,1.004022,1.004022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2448,2021-03-25,-0.054217,0.999458,2.843945,1.964711,10.0,954.99,387311921085308,0.122665,0.001147,0.122665,1.001227,1.777700,1.730556
2449,2021-03-26,-0.000226,0.999998,2.843938,1.964706,10.0,956.70,388051677647507,0.179059,0.001910,0.179059,1.001791,1.780883,1.733655
2450,2021-03-29,-0.076579,0.999234,2.841760,1.963202,10.0,954.10,386977420485060,-0.271768,-0.002768,-0.271768,0.997282,1.776043,1.728943
2451,2021-03-30,-0.046577,0.999534,2.840437,1.962287,10.0,958.06,388660278311558,0.415051,0.004349,0.415051,1.004151,1.783415,1.736119
2452,2021-03-31,0.480351,1.004804,2.854081,1.971713,10.0,956.17,388147690314283,-0.197274,-0.001319,-0.197274,0.998027,1.779896,1.732694

In [34]:
stock_rtn_all["코스닥연누적수익률(%)"]=(stock_rtn_all["코스닥연누적수익률"]-1)*100
stock_rtn_all["누적수익률(%)"]= (stock_rtn_all["누적수익률"]-1)*100
stock_rtn_all["코스닥누적수익률(%)"]= (stock_rtn_all["코스닥누적수익률"]-1)*100
stock_rtn_all["연누적수익률(%)"]= (stock_rtn_all["연누적수익률"]-1)*100

In [35]:
stock_rtn_all =stock_rtn_all[['투자일자', '일일수익률(%)',"누적수익률(%)","연누적수익률(%)", '코스닥종가', '코스닥수익률(%)', '코스닥누적수익률(%)',"코스닥연누적수익률(%)",'투자연차']]

In [36]:
stock_rtn_all

,투자일자,일일수익률(%),누적수익률(%),연누적수익률(%),코스닥종가,코스닥수익률(%),코스닥누적수익률(%),코스닥연누적수익률(%),투자연차
0,2011-04-04,-0.355076,-0.355076,-0.355076,534.90,0.533774,0.533774,0.533774,1.0
1,2011-04-05,0.089691,-0.265703,-0.265703,537.66,0.515984,1.052513,1.052513,1.0
2,2011-04-06,-0.095384,-0.360834,-0.360834,533.98,-0.684447,0.360862,0.360862,1.0
3,2011-04-07,0.104232,-0.256978,-0.256978,534.97,0.185400,0.546931,0.546931,1.0
4,2011-04-08,-0.355504,-0.611568,-0.611568,534.20,-0.143933,0.402210,0.402210,1.0
...,...,...,...,...,...,...,...,...,...
2448,2021-03-25,-0.054217,184.394454,96.471059,954.99,0.122665,77.769983,73.055596,10.0
2449,2021-03-26,-0.000226,184.393810,96.470614,956.70,0.179059,78.088297,73.365468,10.0
2450,2021-03-29,-0.076579,184.176023,96.320159,954.10,-0.271768,77.604311,72.894317,10.0
2451,2021-03-30,-0.046577,184.043662,96.228718,958.06,0.415051,78.341459,73.611916,10.0
2452,2021-03-31,0.480351,185.408069,97.171305,956.17,-0.197274,77.989638,73.269426,10.0

In [37]:
# 전략누적수익률의 표준편차를 계산한다
Std = ( stock_rtn_all["일일수익률(%)"] - stock_rtn_all["코스닥수익률(%)"] ).std( )

# 전략의 샤프비율을 구하고 출력한다
Sharpe = ( stock_rtn_all["일일수익률(%)"] - stock_rtn_all["코스닥수익률(%)"] )/Std
Sharpe =Sharpe.mean()
print( 'Sharpe ratio: %.2f' % Sharpe )

Sharpe ratio: 0.02

In [38]:
Sharpe *np.sqrt(252)

0.26804198253300227

In [39]:
#mdd 
((100+stock_rtn_all["누적수익률(%)"].min())-(100+stock_rtn_all["누적수익률(%)"].max()))/(stock_rtn_all["누적수익률(%)"].max()+100)

-0.6687365238665384

In [40]:
cagr = (stock_rtn_all
        ["누적수익률(%)"]**(1/10))-1
print(cagr*100)

0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
          ...
2448    68.490254
2449    68.490195
2450    68.470284
2451    68.458173
2452    68.582645
Name: 누적수익률(%), Length: 2453, dtype: float64

In [41]:
Std

0.9205307250894973

In [42]:
stock_rtn_all=stock_rtn_all.set_index('투자일자')

In [43]:
rtn_2011 = stock_rtn_all[stock_rtn_all["투자연차"]==1]
rtn_2012 = stock_rtn_all[stock_rtn_all["투자연차"]==2]
rtn_2013 = stock_rtn_all[stock_rtn_all["투자연차"]==3]
rtn_2014 = stock_rtn_all[stock_rtn_all["투자연차"]==4]
rtn_2015 = stock_rtn_all[stock_rtn_all["투자연차"]==5]
rtn_2016 = stock_rtn_all[stock_rtn_all["투자연차"]==6]
rtn_2017 = stock_rtn_all[stock_rtn_all["투자연차"]==7]
rtn_2018 = stock_rtn_all[stock_rtn_all["투자연차"]==8]
rtn_2019 = stock_rtn_all[stock_rtn_all["투자연차"]==9]
rtn_2020 = stock_rtn_all[stock_rtn_all["투자연차"]==10]

In [44]:
rtn_2011

,일일수익률(%),누적수익률(%),연누적수익률(%),코스닥종가,코스닥수익률(%),코스닥누적수익률(%),코스닥연누적수익률(%),투자연차
투자일자,,,,,,,,
2011-04-04,-0.355076,-0.355076,-0.355076,534.90,0.533774,0.533774,0.533774,1.0
2011-04-05,0.089691,-0.265703,-0.265703,537.66,0.515984,1.052513,1.052513,1.0
2011-04-06,-0.095384,-0.360834,-0.360834,533.98,-0.684447,0.360862,0.360862,1.0
2011-04-07,0.104232,-0.256978,-0.256978,534.97,0.185400,0.546931,0.546931,1.0
2011-04-08,-0.355504,-0.611568,-0.611568,534.20,-0.143933,0.402210,0.402210,1.0
...,...,...,...,...,...,...,...,...
2012-03-26,-0.073293,2.820504,2.820504,523.39,-0.773504,-1.629515,-1.629515,1.0
2012-03-27,0.125685,2.949734,2.949734,521.74,-0.315252,-1.939631,-1.939631,1.0
2012-03-28,-0.160780,2.784211,2.784211,519.56,-0.417833,-2.349359,-2.349359,1.0
2012-03-29,-0.260791,2.516160,2.516160,514.21,-1.029717,-3.354885,-3.354885,1.0
2012-03-30,-0.026294,2.489204,2.489204,519.56,1.040431,-2.349359,-2.349359,1.0

In [45]:
# 전략누적수익률의 표준편차를 계산한다
Std =  ( rtn_2011["일일수익률(%)"] - rtn_2011["코스닥수익률(%)"] ).std( )

# 전략의 샤프비율을 구하고 출력한다
Sharpe = ( rtn_2011["일일수익률(%)"] - rtn_2011["코스닥수익률(%)"] )/Std
Sharpe =Sharpe.mean()
print(((100+rtn_2011["누적수익률(%)"].min())-(100+rtn_2011["누적수익률(%)"].max()))/(rtn_2011["누적수익률(%)"].max()+100))
print(Std)
print( 'Sharpe ratio: %.2f' % Sharpe )
print(Sharpe *np.sqrt(252))
rtn_2011

-0.07107767257042036
1.585771005498641
Sharpe ratio: 0.00
0.04507631335898122

,일일수익률(%),누적수익률(%),연누적수익률(%),코스닥종가,코스닥수익률(%),코스닥누적수익률(%),코스닥연누적수익률(%),투자연차
투자일자,,,,,,,,
2011-04-04,-0.355076,-0.355076,-0.355076,534.90,0.533774,0.533774,0.533774,1.0
2011-04-05,0.089691,-0.265703,-0.265703,537.66,0.515984,1.052513,1.052513,1.0
2011-04-06,-0.095384,-0.360834,-0.360834,533.98,-0.684447,0.360862,0.360862,1.0
2011-04-07,0.104232,-0.256978,-0.256978,534.97,0.185400,0.546931,0.546931,1.0
2011-04-08,-0.355504,-0.611568,-0.611568,534.20,-0.143933,0.402210,0.402210,1.0
...,...,...,...,...,...,...,...,...
2012-03-26,-0.073293,2.820504,2.820504,523.39,-0.773504,-1.629515,-1.629515,1.0
2012-03-27,0.125685,2.949734,2.949734,521.74,-0.315252,-1.939631,-1.939631,1.0
2012-03-28,-0.160780,2.784211,2.784211,519.56,-0.417833,-2.349359,-2.349359,1.0
2012-03-29,-0.260791,2.516160,2.516160,514.21,-1.029717,-3.354885,-3.354885,1.0
2012-03-30,-0.026294,2.489204,2.489204,519.56,1.040431,-2.349359,-2.349359,1.0

In [46]:
# 전략누적수익률의 표준편차를 계산한다
Std = ( rtn_2012["일일수익률(%)"] - rtn_2012["코스닥수익률(%)"] ).std( )

# 전략의 샤프비율을 구하고 출력한다
Sharpe = ( rtn_2012["일일수익률(%)"] - rtn_2012["코스닥수익률(%)"] )/Std
Sharpe =Sharpe.mean()
print(((100+rtn_2012["누적수익률(%)"].min())-(100+rtn_2012["누적수익률(%)"].max()))/(rtn_2012["누적수익률(%)"].max()+100))
print(Std)
print( 'Sharpe ratio: %.2f' % Sharpe )
print(Sharpe *np.sqrt(252))
rtn_2012

-0.15007542057895024
0.7931029545390292
Sharpe ratio: 0.03
0.4500245672984633

,일일수익률(%),누적수익률(%),연누적수익률(%),코스닥종가,코스닥수익률(%),코스닥누적수익률(%),코스닥연누적수익률(%),투자연차
투자일자,,,,,,,,
2012-04-03,-0.397841,2.081460,-0.397841,515.83,-1.144117,-3.466596,-1.144117,2.0
2012-04-04,-0.976715,1.084415,-1.370670,502.97,-2.493069,-5.873241,-3.608662,2.0
2012-04-05,-0.501582,0.577394,-1.865378,503.34,0.073563,-5.803998,-3.537754,2.0
2012-04-06,-0.018427,0.558860,-1.883461,503.41,0.013907,-5.790899,-3.524339,2.0
2012-04-09,-1.023015,-0.469873,-2.887208,486.80,-3.299497,-8.899325,-6.707551,2.0
...,...,...,...,...,...,...,...,...
2013-03-25,0.022182,15.293957,12.493758,549.56,-0.306576,2.845700,5.320046,2.0
2013-03-26,-0.078143,15.203863,12.405852,549.90,0.061868,2.909328,5.385205,2.0
2013-03-27,0.155812,15.383365,12.580994,548.72,-0.214584,2.688501,5.159065,2.0
2013-03-28,1.004154,16.541992,13.711481,552.64,0.714390,3.422097,5.910310,2.0
2013-03-29,-0.108209,16.415883,13.588435,555.02,0.430660,3.867495,6.366424,2.0

In [47]:
# 전략누적수익률의 표준편차를 계산한다
Std =  ( rtn_2013["일일수익률(%)"] - rtn_2013["코스닥수익률(%)"] ).std( )

# 전략의 샤프비율을 구하고 출력한다
Sharpe = ( rtn_2013["일일수익률(%)"] - rtn_2013["코스닥수익률(%)"] )/Std
Sharpe =Sharpe.mean()
print(((100+rtn_2013["누적수익률(%)"].min())-(100+rtn_2013["누적수익률(%)"].max()))/(rtn_2013["누적수익률(%)"].max()+100))
print(Std)
print( 'Sharpe ratio: %.2f' % Sharpe )
print(Sharpe *np.sqrt(252))
rtn_2013

-0.13390963595005753
0.5062988034111985
Sharpe ratio: 0.01
0.09608556175815085

,일일수익률(%),누적수익률(%),연누적수익률(%),코스닥종가,코스닥수익률(%),코스닥누적수익률(%),코스닥연누적수익률(%),투자연차
투자일자,,,,,,,,
2013-04-02,0.430780,16.917380,0.430780,552.83,-0.205787,3.653749,-0.205787,3.0
2013-04-03,0.443656,17.436091,0.876348,557.96,0.927953,4.615606,0.720256,3.0
2013-04-04,0.083939,17.534665,0.961022,555.23,-0.489282,4.103740,0.227449,3.0
2013-04-05,-0.784170,16.612993,0.169316,547.51,-1.390415,2.656267,-1.166128,3.0
2013-04-08,-2.889263,13.243737,-2.724840,528.78,-3.420942,-0.855545,-4.547178,3.0
...,...,...,...,...,...,...,...,...
2014-03-25,-0.589866,13.696062,-2.336297,539.05,-1.200513,1.070045,-2.693287,3.0
2014-03-26,1.058655,14.899711,-1.302376,544.13,0.942399,2.022528,-1.776269,3.0
2014-03-27,-0.126342,14.754545,-1.427072,541.46,-0.490692,1.521912,-2.258245,3.0
2014-03-28,0.494427,15.321922,-0.939701,544.10,0.487571,2.016903,-1.781685,3.0
2014-03-31,-0.066037,15.245767,-1.005117,541.58,-0.463150,1.544412,-2.236583,3.0

In [48]:
# 전략누적수익률의 표준편차를 계산한다
Std =  ( rtn_2014["일일수익률(%)"] - rtn_2014["코스닥수익률(%)"] ).std( )

# 전략의 샤프비율을 구하고 출력한다
Sharpe = ( rtn_2014["일일수익률(%)"] - rtn_2014["코스닥수익률(%)"] )/Std
Sharpe =Sharpe.mean()
print(((100+rtn_2014["누적수익률(%)"].min())-(100+rtn_2014["누적수익률(%)"].max()))/(rtn_2014["누적수익률(%)"].max()+100))
print(Std)
print( 'Sharpe ratio: %.2f' % Sharpe )
print(Sharpe *np.sqrt(252))
rtn_2014

-0.1753292812105384
0.6553607728652531
Sharpe ratio: -0.01
-0.13474522892436328

,일일수익률(%),누적수익률(%),연누적수익률(%),코스닥종가,코스닥수익률(%),코스닥누적수익률(%),코스닥연누적수익률(%),투자연차
투자일자,,,,,,,,
2014-04-02,0.524932,15.850729,0.524932,557.65,1.560793,3.129309,1.560793,4.0
2014-04-03,0.050009,15.908665,0.575204,557.01,-0.114767,3.010951,1.444234,4.0
2014-04-04,0.477531,16.462165,1.055481,560.44,0.615788,3.645280,2.068915,4.0
2014-04-07,0.071277,16.545175,1.127510,554.23,-1.108058,2.496830,0.937933,4.0
2014-04-08,-0.136909,16.385613,0.989057,554.07,-0.028869,2.467240,0.908793,4.0
...,...,...,...,...,...,...,...,...
2015-03-25,0.320346,34.914695,17.066942,651.05,1.430196,20.402290,18.571064,4.0
2015-03-26,0.392940,35.444830,17.526946,642.53,-1.308655,18.826639,17.019378,4.0
2015-03-27,-0.658801,34.552518,16.752677,640.12,-0.375080,18.380944,16.580462,4.0
2015-03-30,0.464996,35.178182,17.295572,646.74,1.034181,19.605218,17.786115,4.0
2015-03-31,0.230383,35.489609,17.565801,650.49,0.579831,20.298726,18.469076,4.0

In [49]:
# 전략누적수익률의 표준편차를 계산한다
Std = ( rtn_2015["일일수익률(%)"] - rtn_2015["코스닥수익률(%)"] ).std( )

# 전략의 샤프비율을 구하고 출력한다
Sharpe = ( rtn_2015["일일수익률(%)"] - rtn_2015["코스닥수익률(%)"] )/Std
Sharpe =Sharpe.mean()
print(((100+rtn_2015["누적수익률(%)"].min())-(100+rtn_2015["누적수익률(%)"].max()))/(rtn_2015["누적수익률(%)"].max()+100))
print(Std)
print( 'Sharpe ratio: %.2f' % Sharpe )
print(Sharpe *np.sqrt(252))
rtn_2015

-0.14690686230984984
1.0046682285465038
Sharpe ratio: -0.01
-0.23697931889424428

,일일수익률(%),누적수익률(%),연누적수익률(%),코스닥종가,코스닥수익률(%),코스닥누적수익률(%),코스닥연누적수익률(%),투자연차
투자일자,,,,,,,,
2015-04-02,0.156339,35.701433,0.156339,650.57,0.052289,20.361629,0.052289,5.0
2015-04-03,0.885043,36.902448,1.042766,658.04,1.148224,21.743650,1.201113,5.0
2015-04-06,0.207022,37.185866,1.251946,662.15,0.624582,22.504039,1.833197,5.0
2015-04-07,0.006991,37.195456,1.259024,666.83,0.706788,23.369883,2.552943,5.0
2015-04-08,0.992068,38.556529,2.263583,668.03,0.179956,23.591895,2.737493,5.0
...,...,...,...,...,...,...,...,...
2016-03-25,-0.439143,42.254849,4.993180,683.20,-0.445895,26.398489,5.070514,5.0
2016-03-28,-1.084377,40.712270,3.854658,676.51,-0.979215,25.160775,4.041647,5.0
2016-03-29,0.048643,40.780716,3.905175,686.50,1.476697,27.009020,5.578026,5.0
2016-03-30,-0.117322,40.615550,3.783272,691.13,0.674436,27.865614,6.290082,5.0
2016-03-31,0.010033,40.629659,3.793685,688.38,-0.397899,27.356838,5.867155,5.0

In [50]:
# 전략누적수익률의 표준편차를 계산한다
Std = ( rtn_2016["일일수익률(%)"] - rtn_2016["코스닥수익률(%)"] ).std( )

# 전략의 샤프비율을 구하고 출력한다
Sharpe = ( rtn_2016["일일수익률(%)"] - rtn_2016["코스닥수익률(%)"] )/Std
Sharpe =Sharpe.mean()
print(((100+rtn_2016["누적수익률(%)"].min())-(100+rtn_2016["누적수익률(%)"].max()))/(rtn_2016["누적수익률(%)"].max()+100))
print(Std)
print( 'Sharpe ratio: %.2f' % Sharpe )
print(Sharpe *np.sqrt(252))
rtn_2016

-0.2537412629787425
0.6627848440978316
Sharpe ratio: 0.22
3.5635502320914267

,일일수익률(%),누적수익률(%),연누적수익률(%),코스닥종가,코스닥수익률(%),코스닥누적수익률(%),코스닥연누적수익률(%),투자연차
투자일자,,,,,,,,
2016-04-04,1.397305,42.594684,1.397305,696.98,0.910684,28.516656,0.910684,6.0
2016-04-05,0.062207,42.683388,1.460381,695.70,-0.183649,28.280636,0.725362,6.0
2016-04-06,0.463296,43.344434,1.930443,694.03,-0.240046,27.972703,0.483574,6.0
2016-04-07,0.308566,43.786747,2.244966,697.13,0.446667,28.544315,0.932401,6.0
2016-04-08,-0.211381,43.482809,2.028840,697.10,-0.004303,28.538783,0.928057,6.0
...,...,...,...,...,...,...,...,...
2017-03-27,-0.684584,77.249926,26.040216,607.07,-0.182512,11.938085,-12.106734,6.0
2017-03-28,0.332033,77.838455,26.458712,612.28,0.858221,12.898760,-11.352416,6.0
2017-03-29,0.269431,78.317607,26.799431,613.63,0.220487,13.147688,-11.156959,6.0
2017-03-30,0.783958,79.715542,27.793486,614.68,0.171113,13.341298,-11.004937,6.0
2017-03-31,0.730962,81.029195,28.727608,619.28,0.748357,14.189496,-10.338936,6.0

In [51]:
# 전략누적수익률의 표준편차를 계산한다
Std =  ( rtn_2017["일일수익률(%)"] - rtn_2017["코스닥수익률(%)"] ).std( )

# 전략의 샤프비율을 구하고 출력한다
Sharpe = ( rtn_2017["일일수익률(%)"] - rtn_2017["코스닥수익률(%)"] )/Std
Sharpe =Sharpe.mean()
print(((100+rtn_2017["누적수익률(%)"].min())-(100+rtn_2017["누적수익률(%)"].max()))/(rtn_2017["누적수익률(%)"].max()+100))
print(Std)
print( 'Sharpe ratio: %.2f' % Sharpe )
print(Sharpe *np.sqrt(252))
rtn_2017

-0.15731264235468734
0.9801597767328881
Sharpe ratio: -0.16
-2.530472364260242

,일일수익률(%),누적수익률(%),연누적수익률(%),코스닥종가,코스닥수익률(%),코스닥누적수익률(%),코스닥연누적수익률(%),투자연차
투자일자,,,,,,,,
2017-04-04,0.555577,82.034951,0.555577,625.49,-0.482085,13.639005,-0.482085,7.0
2017-04-05,1.314977,84.428668,1.877859,630.17,0.748213,14.489268,0.262521,7.0
2017-04-06,0.057174,84.534114,1.936107,630.46,0.046019,14.541955,0.308662,7.0
2017-04-07,0.985480,86.352660,2.940667,633.32,0.453637,15.061560,0.763699,7.0
2017-04-10,-2.064075,82.506201,0.815894,619.41,-2.196362,12.534391,-1.449437,7.0
...,...,...,...,...,...,...,...,...
2018-03-26,1.614948,72.927813,-4.475180,853.69,2.893887,55.098375,35.825431,7.0
2018-03-27,0.148410,73.184455,-4.333412,858.84,0.603263,56.034027,36.644816,7.0
2018-03-28,-1.101719,71.276448,-5.387389,850.97,-0.916352,54.604205,35.392668,7.0
2018-03-29,0.821200,72.682970,-4.610430,865.99,1.765045,57.333038,37.782409,7.0
2018-03-30,0.045513,72.761564,-4.567015,871.09,0.588921,58.259606,38.593839,7.0

In [52]:
# 전략누적수익률의 표준편차를 계산한다
Std = ( rtn_2018["일일수익률(%)"] - rtn_2018["코스닥수익률(%)"] ).std( )

# 전략의 샤프비율을 구하고 출력한다
Sharpe = ( rtn_2018["일일수익률(%)"] - rtn_2018["코스닥수익률(%)"] )/Std
Sharpe =Sharpe.mean()
print(((100+rtn_2018["누적수익률(%)"].min())-(100+rtn_2018["누적수익률(%)"].max()))/(rtn_2018["누적수익률(%)"].max()+100))
print(Std)
print( 'Sharpe ratio: %.2f' % Sharpe )
print(Sharpe *np.sqrt(252))
rtn_2018

-0.3211003151317277
0.9404433816244363
Sharpe ratio: 0.07
1.0813941788730757

,일일수익률(%),누적수익률(%),연누적수익률(%),코스닥종가,코스닥수익률(%),코스닥누적수익률(%),코스닥연누적수익률(%),투자연차
투자일자,,,,,,,,
2018-04-03,0.234099,73.165996,0.234099,872.32,0.520857,59.083913,0.520857,8.0
2018-04-04,-1.164154,71.150077,-0.932781,862.51,-1.124587,57.294876,-0.609587,8.0
2018-04-05,1.898775,74.399831,0.948283,868.93,0.744339,58.465683,0.130214,8.0
2018-04-06,-1.362769,72.023165,-0.427409,867.96,-0.111632,58.288785,0.018437,8.0
2018-04-09,0.298795,72.537162,-0.129891,874.44,0.746578,59.470535,0.765153,8.0
...,...,...,...,...,...,...,...,...
2019-03-25,-2.284901,69.866249,-1.675902,727.21,-2.252779,32.620383,-16.200737,8.0
2019-03-26,1.201337,71.906916,-0.494698,736.81,1.320114,34.371123,-15.094492,8.0
2019-03-27,-1.190593,69.860205,-1.679401,728.45,-1.134621,32.846520,-16.057847,8.0
2019-03-28,-1.397007,67.487246,-3.052946,719.72,-1.198435,31.254441,-17.063840,8.0
2019-03-29,0.918562,69.025720,-2.162427,729.31,1.332463,33.003357,-15.958746,8.0

In [53]:
# 전략누적수익률의 표준편차를 계산한다
Std =  ( rtn_2019["일일수익률(%)"] - rtn_2019["코스닥수익률(%)"] ).std( )

# 전략의 샤프비율을 구하고 출력한다
Sharpe = ( rtn_2019["일일수익률(%)"] - rtn_2019["코스닥수익률(%)"] )/Std
Sharpe =Sharpe.mean()
print(((100+rtn_2019["누적수익률(%)"].min())-(100+rtn_2019["누적수익률(%)"].max()))/(rtn_2019["누적수익률(%)"].max()+100))
print(Std)
print( 'Sharpe ratio: %.2f' % Sharpe )
print(Sharpe *np.sqrt(252))
rtn_2019

-0.3327076352159722
0.8030472575701816
Sharpe ratio: 0.04
0.6872365373741292

,일일수익률(%),누적수익률(%),연누적수익률(%),코스닥종가,코스닥수익률(%),코스닥누적수익률(%),코스닥연누적수익률(%),투자연차
투자일자,,,,,,,,
2019-04-02,-0.771504,67.721681,-0.771504,739.57,0.374588,33.501572,0.374588,9.0
2019-04-03,0.636485,68.789205,-0.139929,749.30,1.315629,35.257957,1.695145,9.0
2019-04-04,0.226824,69.172058,0.086577,751.58,0.304284,35.669526,2.004587,9.0
2019-04-05,0.734804,70.415142,0.822018,751.71,0.017297,35.692992,2.022231,9.0
2019-04-08,0.552632,71.356910,1.379192,751.92,0.027936,35.730900,2.050732,9.0
...,...,...,...,...,...,...,...,...
2020-03-25,4.231620,35.547945,-19.806320,505.68,5.262281,-8.718479,-31.369010,9.0
2020-03-26,0.443332,36.148872,-19.450796,516.61,2.161446,-6.745478,-29.885588,9.0
2020-03-27,0.601248,36.967464,-18.966496,522.83,1.204003,-5.622691,-29.041408,9.0
2020-03-30,2.247313,40.045552,-17.145419,542.11,3.687623,-2.142411,-26.424723,9.0
2020-03-31,3.360170,44.751321,-14.361364,569.07,4.973160,2.724204,-22.765706,9.0

In [54]:
# 전략누적수익률의 표준편차를 계산한다
Std = ( rtn_2020["일일수익률(%)"] - rtn_2020["코스닥수익률(%)"] ).std( )

# 전략의 샤프비율을 구하고 출력한다
Sharpe = ( rtn_2020["일일수익률(%)"] - rtn_2020["코스닥수익률(%)"] )/Std
Sharpe =Sharpe.mean()
print(((100+rtn_2020["누적수익률(%)"].min())-(100+rtn_2020["누적수익률(%)"].max()))/(rtn_2020["누적수익률(%)"].max()+100))
print(Std)
print( 'Sharpe ratio: %.2f' % Sharpe )
print(Sharpe *np.sqrt(252))

-0.4836567254582506
0.8145716068644532
Sharpe ratio: 0.06
1.0039343243175003

In [55]:
stcok_rtn_2019=stock_rtn_all[stock_rtn_all["투자연차"]!=10]
stcok_rtn_2019

,일일수익률(%),누적수익률(%),연누적수익률(%),코스닥종가,코스닥수익률(%),코스닥누적수익률(%),코스닥연누적수익률(%),투자연차
투자일자,,,,,,,,
2011-04-04,-0.355076,-0.355076,-0.355076,534.90,0.533774,0.533774,0.533774,1.0
2011-04-05,0.089691,-0.265703,-0.265703,537.66,0.515984,1.052513,1.052513,1.0
2011-04-06,-0.095384,-0.360834,-0.360834,533.98,-0.684447,0.360862,0.360862,1.0
2011-04-07,0.104232,-0.256978,-0.256978,534.97,0.185400,0.546931,0.546931,1.0
2011-04-08,-0.355504,-0.611568,-0.611568,534.20,-0.143933,0.402210,0.402210,1.0
...,...,...,...,...,...,...,...,...
2020-03-25,4.231620,35.547945,-19.806320,505.68,5.262281,-8.718479,-31.369010,9.0
2020-03-26,0.443332,36.148872,-19.450796,516.61,2.161446,-6.745478,-29.885588,9.0
2020-03-27,0.601248,36.967464,-18.966496,522.83,1.204003,-5.622691,-29.041408,9.0
2020-03-30,2.247313,40.045552,-17.145419,542.11,3.687623,-2.142411,-26.424723,9.0
2020-03-31,3.360170,44.751321,-14.361364,569.07,4.973160,2.724204,-22.765706,9.0

In [56]:
# 전략누적수익률의 표준편차를 계산한다
Std =  ( stcok_rtn_2019["일일수익률(%)"] - stcok_rtn_2019["코스닥수익률(%)"] ).std( )

# 전략의 샤프비율을 구하고 출력한다
Sharpe = ( stcok_rtn_2019["일일수익률(%)"] - stcok_rtn_2019["코스닥수익률(%)"] )/Std
Sharpe =Sharpe.mean()
print(((100+stcok_rtn_2019["누적수익률(%)"].min())-(100+stcok_rtn_2019["누적수익률(%)"].max()))/(stcok_rtn_2019["누적수익률(%)"].max()+100))
print(Std)
print( 'Sharpe ratio: %.2f' % Sharpe )
print(Sharpe *np.sqrt(252))
cagr = (stcok_rtn_2019
        ["누적수익률(%)"]**(1/9))-1
print(cagr*100)

-0.5252741945245901
0.9316260704904051
Sharpe ratio: 0.01
0.19683723203721773
투자일자
2011-04-04          NaN
2011-04-05          NaN
2011-04-06          NaN
2011-04-07          NaN
2011-04-08          NaN
                ...
2020-03-25    48.700600
2020-03-26    48.977828
2020-03-27    49.348954
2020-03-30    50.682073
2020-03-31    52.553745
Name: 누적수익률(%), Length: 2208, dtype: float64

In [57]:
# import matplotlib.pyplot as plt

# plt.figure(figsize=(15,10))
# plt.plot(stock_rtn_all["누적수익률(%)"],label='포트폴리오수익률')
# plt.plot(stock_rtn_all["코스닥누적수익률(%)"],label="코스닥수익률")
# plt.legend(fontsize=16)

# plt.show()

In [58]:
# import pandas as pd
# import seaborn as sns
# sns.set(rc={'figure.figsize':(100,200)})

# fig, axes = plt.subplots(5,2)
# # sns.lineplot(x=rtn_2011['투자일자'],y='수익률',data=rtn_2011[["연누적수익률(%)","코스닥연누적수익률(%)"]])
# axes[0,0].plot(rtn_2011[["연누적수익률(%)","코스닥연누적수익률(%)"]])

# axes[0,1].plot(rtn_2012[["연누적수익률(%)","코스닥연누적수익률(%)"]])
# axes[1,0].plot(rtn_2013[["연누적수익률(%)","코스닥연누적수익률(%)"]])
# axes[1,1].plot(rtn_2014[["연누적수익률(%)","코스닥연누적수익률(%)"]])
# axes[2,0].plot(rtn_2015[["연누적수익률(%)","코스닥연누적수익률(%)"]])
# axes[2,1].plot(rtn_2016[["연누적수익률(%)","코스닥연누적수익률(%)"]])
# axes[3,0].plot(rtn_2017[["연누적수익률(%)","코스닥연누적수익률(%)"]])
# axes[3,1].plot(rtn_2018[["연누적수익률(%)","코스닥연누적수익률(%)"]])
# axes[4,0].plot(rtn_2019[["연누적수익률(%)","코스닥연누적수익률(%)"]])
# axes[4,1].plot(rtn_2020[["연누적수익률(%)","코스닥연누적수익률(%)"]])

In [61]:
stock_rtn_all.to_csv("./dataset/범주혼합.csv",encoding='cp949')