In [24]:
#pykrx 데이터 끌고오기
import pandas as pd
import numpy as np
from pykrx import stock
from pykrx import bond

In [25]:
data = pd.read_csv("../데이터자료/윈저데이터셋.csv", encoding='cp949')
data.head()

,회사명,거래소코드,회계년도,상장일,상장폐지일,산업명,소속코드,[제조]매출액증가율,[제조]유형자산증가율,[제조]비유동자산증가율,...,[제조]기계투자효율,[제조]부가가치율,[제조]노동소득분배율,[제조]자본분배율,[제조]이윤분배율,[제조]유형자산회전율,[제조]이자보상배율(이자비용),year,month,label
0,(주)CMG제약,58820,2011-12-01,2001-08-31,NaN,의료용 물질 및 의약품 제조업,5,56.40,-5.90,-12.89,...,128.51,19.56,89.82,10.18,-43.44,1.77,3.53,2011,12,0
1,(주)CMG제약,58820,2012-12-01,2001-08-31,NaN,의료용 물질 및 의약품 제조업,5,-8.43,-4.12,-16.43,...,10.67,1.66,184.40,-84.40,-181.31,1.71,-7.75,2012,12,0
2,(주)CMG제약,58820,2013-12-01,2001-08-31,NaN,의료용 물질 및 의약품 제조업,5,25.51,16.09,77.05,...,289.40,34.29,71.28,28.72,4.23,2.03,0.70,2013,12,0
3,(주)CMG제약,58820,2014-12-01,2001-08-31,NaN,의료용 물질 및 의약품 제조업,5,11.52,74.30,68.15,...,132.06,31.04,79.30,20.70,2.24,1.54,3.60,2014,12,0
4,(주)CMG제약,58820,2015-12-01,2001-08-31,NaN,의료용 물질 및 의약품 제조업,5,18.85,-5.37,1.66,...,90.92,15.96,144.10,-44.10,-84.58,1.48,-32.22,2015,12,0

In [26]:
# 거래소 코드 6개로 맞춰주기
for i in data.index:
    if len(str(data.loc[i,"거래소코드"])) == 3:
        data.loc[i,"거래소코드"]='000'+str(data.loc[i,"거래소코드"])
    elif len(str(data.loc[i,"거래소코드"])) == 4:
        data.loc[i,"거래소코드"]='00'+str(data.loc[i,"거래소코드"])
    elif len(str(data.loc[i,"거래소코드"])) == 5:
        data.loc[i,"거래소코드"]='0'+str(data.loc[i,"거래소코드"])

In [27]:
#거래소 코드 개별로 추출
a =data["거래소코드"].unique()
a = pd.DataFrame(a)
a.columns=["거래소코드"]
len(a)

1463

In [28]:
#회사명 추출
c = data["회사명"].unique()
c = pd.DataFrame(c)
c.columns=["회사명"]
len(c)

1461

In [29]:
#데이터프레임 일치화
a["회사명"] = c["회사명"]

In [30]:
# 코드와 회사명
a

       거래소코드         회사명
0     058820    (주)CMG제약
1     050120     (주)ES큐브
2     079940      (주)가비아
3     217730  (주)강스템바이오텍
4     114190    (주)강원에너지
...      ...         ...
1458  192410     휴마시스(주)
1459  090710       휴젤(주)
1460  205470     흥구석유(주)
1461  145020         NaN
1462  024060         NaN

[1463 rows x 2 columns]

In [31]:
# 코스닥 개별기업들의 일자별 주가 추출
b=[]
for i in a.index:
    df = stock.get_market_ohlcv("20110101", "20211231", a.loc[i,"거래소코드"])
    b.append(df)

In [32]:
# 각 인덱스에 회사명이랑 거래소코드 넣어주기
for i in a.index:
    b[i]["거래소코드"]=a.loc[i,"거래소코드"]
    b[i]["회사명"] =a.loc[i,"회사명"]

In [33]:
# 기업별 데이터프레임 합하기
data_all = pd.concat(b)

In [34]:
data_all

              시가    고가    저가    종가       거래량   거래소코드       회사명
날짜
2011-01-03  1426  1440  1392  1394    439492  058820  (주)CMG제약
2011-01-04  1417  1417  1325  1329    671688  058820  (주)CMG제약
2011-01-05  1333  1351  1260  1321    470690  058820  (주)CMG제약
2011-01-06  1287  1333  1276  1333    422197  058820  (주)CMG제약
2011-01-07  1300  1363  1287  1319    167534  058820  (주)CMG제약
...          ...   ...   ...   ...       ...     ...       ...
2021-12-24  7000  8450  6890  7550  10615180  024060       NaN
2021-12-27  7270  7290  6960  6980   1037631  024060       NaN
2021-12-28  7080  7520  7060  7160   2100701  024060       NaN
2021-12-29  7160  7700  7100  7230   2085674  024060       NaN
2021-12-30  7350  7370  7160  7160    344290  024060       NaN

[2982043 rows x 7 columns]

In [35]:
data_all=data_all.reset_index()
data_all

                날짜    시가    고가    저가    종가       거래량   거래소코드       회사명
0       2011-01-03  1426  1440  1392  1394    439492  058820  (주)CMG제약
1       2011-01-04  1417  1417  1325  1329    671688  058820  (주)CMG제약
2       2011-01-05  1333  1351  1260  1321    470690  058820  (주)CMG제약
3       2011-01-06  1287  1333  1276  1333    422197  058820  (주)CMG제약
4       2011-01-07  1300  1363  1287  1319    167534  058820  (주)CMG제약
...            ...   ...   ...   ...   ...       ...     ...       ...
2982038 2021-12-24  7000  8450  6890  7550  10615180  024060       NaN
2982039 2021-12-27  7270  7290  6960  6980   1037631  024060       NaN
2982040 2021-12-28  7080  7520  7060  7160   2100701  024060       NaN
2982041 2021-12-29  7160  7700  7100  7230   2085674  024060       NaN
2982042 2021-12-30  7350  7370  7160  7160    344290  024060       NaN

[2982043 rows x 8 columns]

In [36]:
# data_all.to_csv("../데이터자료/일일주식데이터.csv", encoding='cp949')

In [37]:
df = stock.get_index_ohlcv_by_date("20110101", "20211231", "2001")

In [38]:
df_kosdak = df[["종가","상장시가총액"]]
df_kosdak["지수수익률"] = df["종가"].pct_change()
df_kosdak["시총수익률"] = df["상장시가총액"].pct_change()

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_41044\1651253204.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_kosdak["지수수익률"] = df["종가"].pct_change()
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_41044\1651253204.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_kosdak["시총수익률"] = df["상장시가총액"].pct_change()

In [39]:
#코스닥 주가데이터
df_kosdak

코스닥              종가           상장시가총액     지수수익률     시총수익률
날짜
2011-01-03   518.05   99446901806331       NaN       NaN
2011-01-04   521.35   99996408870370  0.006370  0.005526
2011-01-05   523.81  100973551095242  0.004719  0.009772
2011-01-06   527.64  101663579213452  0.007312  0.006834
2011-01-07   530.84  102278943380380  0.006065  0.006053
...             ...              ...       ...       ...
2021-12-24  1007.42  439628750148269  0.004096  0.004129
2021-12-27  1011.36  437280772439099  0.003911 -0.005341
2021-12-28  1027.44  444227877043742  0.015899  0.015887
2021-12-29  1028.05  443469160171658  0.000594 -0.001708
2021-12-30  1033.98  446297029881938  0.005768  0.006377

[2711 rows x 4 columns]

In [40]:
df_kosdak.to_csv("../데이터자료/코스닥주가.csv", encoding='cp949')